DATA:
  BATCH_SIZE: 8
  FILTER:
    MAX_DEPTH: 65
    MAX_OCCLUSION: 2
    MAX_TRUNCATION: 0.5
    MIN_DEPTH: 2
    MIN_HEIGHT: 25
  NUM_WORKERS: 4
  ROOT: final_project_data_kitti
  TEST_SPLIT: val
  TRAIN_SPLIT: train
DESCRIPTION: MonoCon Default Configuration
GPU_ID: 2
MODEL:
  BACKBONE:
    IMAGENET_PRETRAINED: true
    NUM_LAYERS: 34
  HEAD:
    MAX_OBJS: 50
    NUM_CLASSES: 3
OUTPUT_DIR: exps_hyperparam_tuning/double_lr_half_num_epoch/trial_5
PERIOD:
  EVAL_PERIOD: 10
  LOG_PERIOD: 50
SEED: 571540729
SOLVER:
  CLIP_GRAD:
    ENABLE: true
    MAX_NORM: 35
    NORM_TYPE: 2.0
  OPTIM:
    LR: 0.00045
    NUM_EPOCHS: 100
    WEIGHT_DECAY: 1.0e-05
  SCHEDULER:
    ENABLE: true
USE_BENCHMARK: true
VERSION: v1.0.3

